

name: CI/CD for Student Registry App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:


    strategy:
      matrix:
        node-version: [ 20,22,24 ]

    runs-on: ubuntu-latest

    steps:
    - name: Step name:Chene the repository
      uses: actions/checkout@v5
      
    - name: Step name:Use of the Node.js 20 ,22 ,24 version
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}

    - name: Step name:Installing of the dependancies    
      run: npm install
      
    - name: Step name:Run the tests
      run: npm test
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          
