

name: CI/CD for Student Registry App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step name:Chene the repository
      uses: actions/checkout@v4
      
    - name: Step name:Use of the Node.js 24.18.0 version
      uses: actions/setup-node@v4
      with:
        node-version: 24.18.0

    - name: Step name:Installing of the dependancies    
      run: npm install
      
    - name: Step name:Run the tests
      run: npm test
